### ISSUE TITLE
Support compiled into html(the static part)

### ISSUE THREAD

**Issue by zaoqi** [amirouche/forward.scm#2]

**Comment by amirouche** [comment]
Can you develop your idea?

**Comment by zaoqi** [comment]
`define-page` `lambda-page`

**Comment by amirouche** [comment]
What's the point of comiling the static part to html? maybe speed of execution? But I am not sure. There is no notion of page in `forward.scm`.

**Comment by zaoqi** [comment]
Call `view` to get html, in order to support google.

**Comment by amirouche** [comment]
This must be implemented backend side not frontend side.

**Comment by amirouche** [comment]
Also supporting google is minor annoyance in most applications since most of the data lives inside a closed garden. Otherwise said, right now I have no elegant solution to build a CMS in scheme ie. a solution that doesn't involves writing the view twice once in the frontend and once in the backend. And google AFAIK support SPA anyway.
